/******************************************************************************
 * Copyright 2017-2018 Baidu Robotic Vision Authors. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *****************************************************************************/
/*
 * [IMPORTANT] This file is automatically generated by CMake.
 *             Do NOT modify it directly.
 */
#ifndef INCLUDE_DRIVER_FIRMWARE_CONFIG_H_
#define INCLUDE_DRIVER_FIRMWARE_CONFIG_H_

// Define the minimum supported firmware version number
#define MIN_FIRMWARE_VERSION_MAJOR 0
#define MIN_FIRMWARE_VERSION_MINOR 8
#define MIN_FIRMWARE_VERSION_PATCH 5

#endif  // INCLUDE_DRIVER_FIRMWARE_CONFIG_H_
